version: "3"
services:
  traefik-docker:
    image: traefik:v2.9
    container_name: traefik-balancer 
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server1
    ports:
      - 3000:3000
    container_name: server1
  
  server2:
    build:
      context: .
      dockerfile: Dockerfile.server2
    ports:
      - 3001:3001
    container_name: server2