
global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  web:
    address: :80

  websecure:
    address: :443
api:
  insecure: true
  dashboard: true
providers:
  file:
    filename: /etc/traefik/router.yml
    watch: true