[http]
  [http.routers]
    # Define a connection between requests and services
    [http.routers.rotraefik]
      rule = "Host(`is-kiyotaka.co.id`) && PathPrefix(`/`)"
      # If the rule matches, forward to the whoami service (declared below)
      service = "roservices"
  
  [http.services]
     # Define how to reach an existing service on our infrastructure
     [http.services.roservices.loadBalancer]
       [[http.services.roservices.loadBalancer.servers]]
         url = "192.168.50.218:3001"